blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/komikku-app/komikku/issues/new/choose
    about: Issues and requests about the app itself should be opened in Komikku's repository instead
  - name: ğŸ“¦ Extension list
    url: https://komikku-repo.github.io/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Komikku website
    url: https://komikku-app.github.io/docs/guides/troubleshooting/
    about: Guides, troubleshooting, and answers to common questions
